name: Cron Job
on:
  schedule:
    - cron: '0 0 * * *'
jobs:
  update-dns:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run Update DDNS
        env:
          CF_KEY: ${{ secrets.CF_KEY }}
          CF_EMAIL: ${{ secrets.CF_EMAIL }}
          CF_HOST: ${{ secrets.CF_HOST }}
          CF_ZONE: ${{ secrets.CF_ZONE }}
          CF_TYPE: ${{ secrets.CF_TYPE }}
        run: |
          ./ddns/cf-ddns.sh -k $CF_KEY -u $CF_EMAIL -h $CF_HOST -z $CF_ZONE -t $CF_TYPE


